export const fetchClassData = async () => {
  return {
    className: 'Join 302 Math',
    id: 'X58E9647',
    link: 'https://www.classswift.viewsonic.io/',
    students: [
      { id: 1, name: 'Philip', score: 3 },
      { id: 2, name: 'Darrell', score: 6 },
      { id: 3, name: 'Guest', score: 0 },
      { id: 4, name: 'Cody', score: 10 },
      { id: 5, name: 'Guest', score: 0 },
      { id: 6, name: 'Wendy', score: 4 },
      { id: 7, name: 'Esther', score: 6 },
      { id: 8, name: 'Jacob', score: 8 },
      { id: 9, name: 'Bessie', score: 8 },
      { id: 10, name: 'Gloria', score: 3 },
      { id: 11, name: 'Ann', score: 7 },
      { id: 12, name: 'Calvin', score: 7 },
      { id: 13, name: 'Lee', score: 6 },
      { id: 14, name: 'Joe', score: 5 },
      { id: 15, name: 'Guest', score: 0 },
      { id: 16, name: 'Guest', score: 0 },
      { id: 17, name: 'Sue', score: 5 },
      { id: 18, name: 'Emily', score: 5 },
      { id: 19, name: 'Tom', score: 8 },
      { id: 20, name: 'Sarah', score: 3 },
      { id: 21, name: 'Guest', score: 0 },
      { id: 22, name: 'Kevin', score: 1 },
      { id: 23, name: 'Lily', score: 8 },
      { id: 24, name: 'Guest', score: 0 },
      { id: 25, name: 'David', score: 2 },
      { id: 26, name: 'Sophia', score: 9 },
      { id: 27, name: 'James', score: 3 },
      { id: 28, name: 'Guest', score: 0 },
      { id: 29, name: 'Ella', score: 9 },
      { id: 30, name: 'Guest', score: 0 },
    ],
  };
};
